[package]
name = "simplefs"
version = "0.1.0"
authors = ["Allan Calix <contact@allancalix.com>"]
edition = "2018"

[dependencies]
tempfile = "3.1.0"
thiserror = "1.0.15"
zerocopy = "0.3.0"
log = "0.4.8"
