name: action
on:
  pull_request:
    types: ["opened", "edited", "synchronize", "reopened"]
  push:
    branches: 
      - master
jobs:
  cicd:
    name: test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        rust:
          - 1.39.0
          - stable
          - nightly

    steps:
    - name: install dependencies
      if: startsWith(matrix.os, 'ubuntu')
      run: sudo apt-get update && sudo apt-get install -yq libfuse-dev pkg-config
    - name: Install FUSE (macOS)
      if: startsWith(matrix.os, 'macos')
      run: brew update && brew install pkg-config && brew tap homebrew/cask && brew cask install osxfuse
    - name: checkout
      uses: actions/checkout@v2
    - name: rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        override: true
    - name: test
      uses: actions-rs/cargo@v1
      with:
        command: test

