name: ci
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
    types:
    - opened
    - edited
    - synchronize
    - reopened
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - name: install dependencies
      if: startsWith(matrix.os, 'ubuntu')
      run: sudo apt-get update && sudo apt-get install -yq libfuse-dev pkg-config
    - name: Install FUSE (macOS)
      if: startsWith(matrix.os, 'macos')
      run: brew update && brew install pkg-config && brew tap homebrew/cask && brew cask install osxfuse
    - name: checkout
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        override: true
    - uses: actions-rs/cargo@v1
      with:
        command: test
